// Skill levels
export const SKILL_LEVELS = ["Beginner", "Intermediate", "Advanced"] as const;
export type SkillLevel = (typeof SKILL_LEVELS)[number];

// Technologies
export const TECHNOLOGIES = [
  "CSharp",
  "Java",
  "Python",
  "Go",
  "Rust",
  "Ruby",
  "NodeJs",
  "JavaScript",
  "TypeScript",
  "React",
  "Vue",
  "Angular",
  "Html",
  "Css",
  "TailwindCss",
  "Swift",
  "Kotlin",
  "Flutter",
  "ReactNative",
  "Sql",
  "PostgreSql",
  "MongoDb",
  "Redis",
  "Cpp",
  "C",
  "Docker",
  "Kubernetes",
] as const;

export type Technology = (typeof TECHNOLOGIES)[number];

// Display names for technologies (prettier labels)
export const TECHNOLOGY_LABELS: Record<Technology, string> = {
  CSharp: "C#",
  Java: "Java",
  Python: "Python",
  Go: "Go",
  Rust: "Rust",
  Ruby: "Ruby",
  NodeJs: "Node.js",
  JavaScript: "JavaScript",
  TypeScript: "TypeScript",
  React: "React",
  Vue: "Vue",
  Angular: "Angular",
  Html: "HTML",
  Css: "CSS",
  TailwindCss: "Tailwind CSS",
  Swift: "Swift",
  Kotlin: "Kotlin",
  Flutter: "Flutter",
  ReactNative: "React Native",
  Sql: "SQL",
  PostgreSql: "PostgreSQL",
  MongoDb: "MongoDB",
  Redis: "Redis",
  Cpp: "C++",
  C: "C",
  Docker: "Docker",
  Kubernetes: "Kubernetes",
};

// Backend mapping - slug format (must match ProgrammingTechnologyConstants.cs)
export const TECHNOLOGY_TO_BACKEND_MAP: Record<Technology, string> = {
  CSharp: "csharp",
  Java: "java",
  Python: "python",
  Go: "go",
  Rust: "rust",
  Ruby: "ruby",
  NodeJs: "nodejs",
  JavaScript: "javascript",
  TypeScript: "typescript",
  React: "react",
  Vue: "vue",
  Angular: "angular",
  Html: "html",
  Css: "css",
  TailwindCss: "tailwindcss",
  Swift: "swift",
  Kotlin: "kotlin",
  Flutter: "flutter",
  ReactNative: "reactnative",
  Sql: "sql",
  PostgreSql: "postgresql",
  MongoDb: "mongodb",
  Redis: "redis",
  Cpp: "cpp",
  C: "c",
  Docker: "docker",
  Kubernetes: "kubernetes",
};

// Category grouping for better UX
export const TECH_CATEGORIES = {
  "Programming Languages": [
    "CSharp",
    "Java",
    "Python",
    "Go",
    "Rust",
    "Ruby",
    "Cpp",
    "C",
  ],
  "Web Technologies": [
    "JavaScript",
    "TypeScript",
    "NodeJs",
    "React",
    "Vue",
    "Angular",
    "Html",
    "Css",
    "TailwindCss",
  ],
  "Mobile Development": ["Swift", "Kotlin", "Flutter", "ReactNative"],
  "Databases & DevOps": [
    "Sql",
    "PostgreSql",
    "MongoDb",
    "Redis",
    "Docker",
    "Kubernetes",
  ],
} as const;
